### ISSUE TITLE
seeded random is not reproducing exact results

### ISSUE THREAD

**Issue by kwg** [kwg/InfiniteArtGallery#96]
maybe there is a random call that is not using the seed?

**Comment by schrum2** [comment]
Jake's Zelda code had this issue as well, and fixing it was a major nightmare. Start by searching the code for any use of a random number generator, as well as any other means of generating random numbers. However, if it's still not fixed after that, you'll need to look for other sneaky sources of non-determinism. Keep me updated.

**Comment by kwg** [comment]
This seems to be fixed after the refactor. Will continue to keep an eye on it and if the issue returns I will reopen this.
